### ISSUE TITLE
Update to istio 0.8 edit: 1.0

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/Java-MicroProfile-Microservices-on-Istio#40]
https://istio.io/docs/tasks/traffic-management/ingress/

```
In a Kubernetes environment, the Kubernetes Ingress Resource is used to specify  
services that should be exposed outside the cluster. In an Istio service mesh, a  
better approach (which also works in both Kubernetes and other environments)  
is to use a different configuration model, namely Istio Gateway. A Gateway allows  
Istio features, for example, monitoring and route rules, to be applied to traffic  
entering the cluster.
```

Istio is now using its own configuration model rather than a Kubernetes Ingress resource

new yaml file would look like:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice-webapp
spec:
  hosts:
  - "*"
  gateways:
  - microservice-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: webapp-service
        port:
          number: 9080
  - match:
    - uri:
        prefix: /vote
    route:
    - destination:
        host: vote-service
        port:
          number: 9080
  - match:
    - uri:
        prefix: /schedule
    route:
    - destination:
        host: schedule-service
        port:
          number: 9080
  - match:
    - uri:
        prefix: /speaker
    route:
    - destination:
        host: speaker-service
        port:
          number: 9080
  - match:
    - uri:
        prefix: /sessions
    route:
    - destination:
        host: session-service
        port:
          number: 9080
  - route:
    - destination:
        host: webapp-service
        port:
          number: 9080
```

Also, `--includeIPRanges` is deprecated

Explore using this annotation:
```
traffic.sidecar.istio.io/includeOutboundIPRanges: "172.30.0.0/16,172.20.0.0/16,10.10.10.0/24"
```

Verify if Part B will still work or needs changing in new Istio version
