### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by animeshsingh** [IBM/Java-MicroProfile-Microservices-on-Istio#7]
@AnthonyAmanse @mlangbehn please do initial testing
@Tomcli please ensure build is working right - I have asked other external folks to test out as well

**Comment by Tomcli** [comment]
Can you enable Travis for this repository? Currently I don't have permission to enable Travis for this repo.

**Comment by animeshsingh** [comment]
Try now - made you an admin

**Comment by AnthonyAmanse** [comment]
1. `bx plugin install container-registry -r Bluemix` - also provide `bx plugin update container-registry -r Bluemix` for users that already has the plugin. Outdated container-registry results into not detecting their namespaces
2. Typos: 
    * `Then, you can move on to Step 3.` Link is broken and should say _Step 2_
    * `Congratulation` to `Congratulations`
    * `Now you have 2 different versions` to `versions`
3. I think it's also wise to put `istioctl delete route-rule <route-rule>` or `istioctl delete -f <yaml-file>` in the Troubleshooting section if the user chooses not to delete their current Istio control plane.
4. The `cloudant-secret-generator-deploy` Job should be separated from `manifests/deploy-cloudant.yaml` so that it doesn't inject an Istio Envoy in that Job resource. The Job only creates a secret in the cluster and there is no need to have an envoy for that.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cloudant-secret-generator-deploy
  labels:
    app: microprofile-app
spec:
  template:
    metadata:
      name: cloudant-secret-generator-deploy
    spec:
      containers:
      - name: cloudant-secret-generator-deploy
        image: ibmcom/kubernetes:v1.5.2
        command: ["/bin/sh","-c"]
        args: ["/kubectl get secret cloudant-secret || /kubectl create secret generic cloudant-secret --from-literal=dbUsername=admin --from-literal=dbPassword=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;`"]
        resources:
          limits:
            cpu: 100m
      restartPolicy: Never
```
